#!/bin/bash

awk '{if($1!="//"){record=record""$0"\n";if($1=="NAME"){n=$2};if($1=="DESC"){des=$0}}else{r[n]=record;record="";d[n]=des}} END{for(i in r){if(tolower(d[i])~/gag |gag-|envelope|env$|env |env-|env_|gypsy|integrase|retroviral|retrotrans|retro-|reverse transcriptase|protease|coat/){print r[i]>"ss/"i".hmm"}}}' Pfam-A.hmm
